# optional
name: Android Fastlane with Firebase App Distribution Workflow

# when push to master branch execute the job (workflow).
on:
  push:
    branches:
      - main

jobs:
# distribute_to_firebase -> job name (optional) Title in github actions.
  distribute_to_firebase:
  # ubuntu used with android workflow.
    runs-on: ubuntu-latest
    steps:
    # name is optional (like comment of uses).
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.2"
        # bundler-cache ->work flow  تسريع عملية ال 
        bundler-cache: true
        # like cd android in terminal (to access gemfile, bundlare & fastlane) setup ruby in android.
        working-directory: android
        
    - name: Build and Distribute App
      env:
      # FIREBASE_CLI_TOKEN -> secret name in github actions.
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        bundle exec fastlane android firebase_distribution
      working-directory: android