import 'package:flutter/material.dart';

class ColorsManager{
  static const Color primaryColor = Color(0xFF247CFF);
  static const Color darkBlue = Color(0xFF242424);
  static const Color gray = Color(0xFF757575);
  static const Color lightGray = Color(0xFFC2C2C2);
  static const Color lighterGray = Color(0xFFEDEDED);
  static const Color moreLightGray = Color(0xFFFDFDFF);
  static const Color secondaryColor = Color(0xFF42A5F5);
  static const Color accentColor = Color(0xFF64B5F6);
  static const Color backgroundColor = Color(0xFFE3F2FD);
  static const Color textColor = Color(0xFF000000);
  static const Color errorColor = Color(0xFFB00020);
  static const Color successColor = Color(0xFF00C853);
  static const Color warningColor = Color(0xFFFFD600);
  static const Color infoColor = Color(0xFF00B0FF);
  static const Color disabledColor = Color(0xFFBDBDBD);
  static const Color dividerColor = Color(0xFFBDBDBD);
  static const Color transparent = Color(0x00000000);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color grey = Color(0xFF9E9E9E);
  static const Color red = Color(0xFFD32F2F);
  static const Color green = Color(0xFF388E3C);
  static const Color blue = Color(0xFF1976D2);
  static const Color yellow = Color(0xFFFFA000);
  static const Color orange = Color(0xFFFF6F00);
  static const Color purple = Color(0xFF7B1FA2);
  static const Color pink = Color(0xFFC2185B);
  static const Color brown = Color(0xFF795548);
  static const Color cyan = Color(0xFF0097A7);
  static const Color teal = Color(0xFF00796B);
  static const Color indigo = Color(0xFF3F51B5);
  static const Color lime = Color(0xFFCDDC39);
  static const Color amber = Color(0xFFFFC107);
  static const Color deepOrange = Color(0xFFFF5722);
  static const Color deepPurple = Color(0xFF673AB7);
  static const Color lightBlue = Color(0xFF03A9F4);
}